### ISSUE TITLE
.skip note should allow TODO: comments

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/eslint-plugin-dev#17]
I'm running the new eslint rules against Cypress https://github.com/cypress-io/eslint-plugin-dev/issues/14 and it's warning that there is not a note above a skipped test, but looking at the test, it has this:

```js
// TODO: fix this once we implement aborting / restoring / reset
it.skip('can cancel multiple dblclicks', function (done) {
```

Actually most of them have a TODO note

```js
// TODO: fix this with 4.0 updates
describe.skip('element reference loss', () => {
```

```js
// TODO: add an ipv6 lo if to the docker container
it.skip('resolves localhost on ::1 immediately', function () {
```

which seems like it should reasonably pass eslint to me. Can we update the logic to also accept `TODO` comments?

My PR https://github.com/cypress-io/cypress/pull/4723

**Comment by kuceb** [comment]
great point

**Comment by chrisbreiding** [comment]
How about allowing `FIXME` comments too?

**Comment by kuceb** [comment]
@chrisbreiding how about making this configurable :sweat_smile:
