### ISSUE TITLE
Need to explain how to configure editor plugins

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/eslint-plugin-dev#2]
For example how to run eslint plugin for Atom, VSCode, Sublime Text to auto fix linting issues on document save.

**Comment by chrisbreiding** [comment]
Version `1.1.2` has been published to NPM. The full release note can be found at [eslint-plugin-cypress-dev/releases/tag/v1.1.2](https://github.com/cypress-io/eslint-plugin-cypress-dev/releases/tag/v1.1.2).

**Tip:** safely upgrade dependency eslint-plugin-cypress-dev in your project using [next-update](https://github.com/bahmutov/next-update)
