### ISSUE TITLE
experimental decorators?

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/eslint-plugin-dev#4]
I continue to get eslint errors concerning experimental decorators in VSCode. It's more a nuisance than anything. Just wanted to open an issue to consider adding support for experimentalDecorators to our dev config. 

```
Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
```

**Comment by chrisbreiding** [comment]
This appears to be specific to VSCode: https://github.com/Microsoft/vscode/issues/28097. I don't think it can be fixed via eslint.

Does adding a `jsconfig.json` as noted in the above issue fix it?

**Comment by jennifer-shehane** [comment]
yep, I gotta add another config file to every mobx project...dunno how I feel about this, VSCode.

![](https://media.giphy.com/media/kaq6GnxDlJaBq/giphy.gif)

**Comment by smhammadshakil** [comment]
1)
<---
To fix this add 
"javascript.implicitProjectConfig.experimentalDecorators": true,
 in user settings of VScode
--->
2) 
<---
To applying observable on the class:
This will fix the build issue

import React, { Component } from 'react';
import { observer }  from 'abc-library';

class App extends Component {
  constructor() {
    super();
 }
 render() {
    return (
  ...
    );
  }
}
export default observer(App)
-->
