### ISSUE TITLE
no-debugger only when in production

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/eslint-plugin-dev#5]
I saw this in someones `eslintrc` file on the internet. This would help with issues with my autofix eslint on save. I always have to wrestling with my IDE to disable removing debugger on save. Would this work for us?

```
// allow debugger during development
'no-debugger': process.env.NODE_ENV === 'production' ? 2 : 0
```

**Comment by chrisbreiding** [comment]
I just worry this will let debuggers slip through in pre-commit or pre-push hooks, which is ideally where we want to catch them. Does VSCode not have an easy way to disable rules from auto-fixes? It's really easy in Atom 😄.

**Comment by jennifer-shehane** [comment]
Yeah, it does make me worry too. It's just annoying.

Solution for vscode, add this to vscode `settings.json`. Should still catch errors in commit/push hooks
```
  "eslint.options": {
    "rules": {
      "no-debugger": "off"
    }
  }
```
